language: node_js
node_js:
  - "10.0"
script:
  - npm install
  - cd functions
  - npm install
  - cd ../
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN